### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ruudhanegraaf** [aswinkumar863/sort-editors-vscode#1]
Hi Aswin.

This looks promising. :-)
Two request/suggestions which would would make it fit my own needs even more:

- Do an automatic 'Sort Active Editor' after each save, to make sure that when you save a file - either a new file, or an existing file using a new name - the order is adjusted.

- Unsaved files are sorted as starting with the U(ntitled). It would be great if you could also have the option to sort the tabs using the tab title, more in line with how the editors are sorted in the open editors view of the side bar. 

So this...

<img width="878" alt="image" src="https://user-images.githubusercontent.com/48607712/172448030-601d9488-9bcd-48a4-9dd0-0017d71eec20.png">

... as opposed to...

<img width="853" alt="image" src="https://user-images.githubusercontent.com/48607712/172447697-9bbfc3bb-d047-4abe-9de0-2b9c6b8aaebf.png">

Regards,
Ruud

**Comment by aswinkumar863** [comment]
> - Do an automatic 'Sort Active Editor' after each save, to make sure that when you save a file - either a new file, or an existing file using a new name - the order is adjusted.

The extension should allow the users to reorder the tabs if needed. While considering performance, it's not required to sort opened editor on each save. Sorting editors while its opening is enough. Only the untitled editor will be sorted on save.

> - Unsaved files are sorted as starting with the U(ntitled). It would be great if you could also have the option to sort the tabs using the tab title, more in line with how the editors are sorted in the open editors view of the side bar.

Doing this will make the untitled editor jumps to a new position on entering the first character. I tried implementing this and felt the user experience is bad and confusing. So It's better to keep sorting by name or path as existing.


Anyhow, thank you for using my extension and making good suggestions. I have reduced the sorting delay and optimized the untitled editor sorting with a new release (v2.0.0). Now the untitled editor will be sorted when it's saved.

**Comment by ruudhanegraaf** [comment]
Hi Aswin,

Thanks and you're welcome. :-)

> Doing this will make the untitled editor jumps to a new position on entering the first character. I tried implementing this and felt the user experience is bad and confusing.
I get what you're saying. What I had in mind was only doing the sorting for the untitled files when opening VSCode or when using the manual sort commands. 

Installing 2.0 now... :-)

Regards,
Ruud
